# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='brief',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
