# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170925_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=256, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='document',
            field=models.FileField(blank=True, upload_to='doc'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='video',
            field=models.FileField(blank=True, upload_to='video'),
        ),
    ]
