# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170925_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='manual',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
